Repository LiveSplit/splits-io-api, pull requests merged in 2019-12, with the labels that each got.

#6 Update to dependencies to Hyper 0.13.0
  .github/workflows/rust.yml
  Cargo.toml
  src/lib.rs
  src/platform/native.rs
  src/platform/wasm.rs
  src/run.rs
Labels: enhancement

#8 Add documentation
  Cargo.toml
  README.md
  src/category.rs
  src/game.rs
  src/lib.rs
  src/race.rs
  src/run.rs
  src/runner.rs
  src/schema.rs
Labels: documentation, enhancement, user feature

#11 Switch to hyper-rustls
  Cargo.toml
  src/lib.rs
  src/platform/native.rs
Labels: enhancement, user feature

#12 Reenable 32-bit Linux Builds
  .github/workflows/rust.yml
Labels: enhancement

#16 Add methods for better traversal of the API
  Cargo.toml
  README.md
  src/category.rs
  src/game.rs
  src/lib.rs
  src/platform/wasm.rs
  src/race.rs
  src/run.rs
  src/runner.rs
  tests/tests.rs
Labels: enhancement, user feature
